# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Simpsons stuff
# 33 Jobs
@snpp_owner=Job.create(name: "Power plant owner")
@media_mogul=Job.create(name: "Media mogul")
@secretary=Job.create(name: "Personal assistant or secretary")
@mob=Job.create(name: "Mob operative")
@politics=Job.create(name: "Political figure")
@police=Job.create(name: "Police")
@minister=Job.create(name: "Minister")
@reverends_wife=Job.create(name: "Reverend's wife")
@snpp_worker=Job.create(name: "Nuclear safety inspector")
@homemaker=Job.create(name: "Homemaker")
@hyperactive_child=Job.create(name: "Hyperactive child")
@critical_thinker=Job.create(name: "Level-headed critical thinker")
@student=Job.create(name: "Student")
@comptroller=Job.create(name: "Comptroller")
@educator=Job.create(name: "Public school educator")
@shop_keep=Job.create(name: "Store keep")
@cafeteria_worker=Job.create(name: "Cafeteria worker")
@oppressed_youth=Job.create(name: "Oppressed youth") # Young person becoming a product of their environment
@scientist=Job.create(name: "Scientist, inventor.")
@drunkard=Job.create(name: "Town Lush")
@doctor=Job.create(name: "Doctor")
@judge=Job.create(name: "Judge")
@attorney=Job.create(name: "Attorney")
@real_estate=Job.create(name: "Real estate agent")
@school_bully=Job.create(name: "School bully")
@tv_personality=Job.create(name: "TV personality")
@bus_driver=Job.create(name: "Bus driver")
@actor=Job.create(name: "Actor")
@helicopter_pilot=Job.create(name: "Helicopter reporter")
@superhero=Job.create(name: "Comic book superhero")
@mastermind=Job.create(name: "Criminal mastermind")
@tavern_keep=Job.create(name: "Suds slinger")
@janitor=Job.create(name: "Janitor")

# 65 People
@burns=User.create(name: "Charles Montgomery Burns", public_id: 'burns', manager: nil, job: @snpp_owner, level: 3, url: "https://en.wikipedia.org/wiki/Mr._Burns", blurb: "Owner of the Springfield Nuclear Power Plant.")
@roger_meyers=User.create(name: "Roger Meyers, Jr.", public_id: 'roger_meyers', manager: nil, job: @media_mogul, level: 3, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Roger_Meyers_Jr.", blurb: "Chairman of Itchy & Scratchy International.")
@krusty=User.create(name: "Krusty the Clown", public_id: 'krusty', manager: @roger_meyers, job: @tv_personality, level: 3, url:"https://en.wikipedia.org/wiki/Krusty_the_Clown", blurb: "TV show clown host, original name Herschel Shmoikel Pinchas Yerucham Krustofski.")
@sideshow_bob=User.create(name: "Sideshow Bob", public_id: 'sideshow_bob', manager: @krusty, job: @mastermind, level: 2, url: "https://en.wikipedia.org/wiki/Sideshow_Bob", blurb: "Criminal mastermind and Krusty the Clown Show ex-operator and sidekick.")
@sideshow_mel=User.create(name: "Sideshow Mel", public_id: 'sideshow_mel', manager: @krusty, job: @tv_personality, level: 2, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Sideshow_Mel", blurb: "The Krusty the Clown Show sidekick.")
@mr_teeny=User.create(name: "Mr. Teeny", public_id: 'mr_teeny', manager: @krusty, job: @tv_personality, level: 1, url: "https://en.wikipedia.org/wiki/List_of_celebrities_in_The_Simpsons#Mr._Teeny", blurb: "The Krusty the Clown Show trained monkey.")
@radioactive_man=User.create(name: "Radioactive Man", public_id: 'radioactive_man', manager: @roger_meyers, job: @superhero, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Radioactive_Man", blurb: "Comic book superhero.")
@bailey=User.create(name: "Mary Bailey", public_id: 'bailey', manager: @burns, job: @politics, level: 3, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Mary_Bailey", blurb: "Governor of Springfield's state.")
@smithers=User.create(name: "Waylon Smithers", public_id: 'smithers', manager: @burns, job: @secretary, url: "https://en.wikipedia.org/wiki/Waylon_Smithers", blurb: "Mr. Burns's personal assistant.")
@fat_tony=Athlete.create(name: "Fat Tony", public_id: 'fat_tony', manager: @burns, job: @mob, level: 3, url: "https://en.wikipedia.org/wiki/Fat_Tony", blurb: "Mob boss.")
@quimby=User.create(name: "Mayor \"Diamond Joe\" Quimby", public_id: 'quimby', manager: @fat_tony, job: @politics, level: 2, url: "https://en.wikipedia.org/wiki/Mayor_Quimby", blurb: "Mayor of Springfield.")
@wiggum=User.create(name: "Chief Clancy Wiggum", public_id: 'wiggum', manager: @quimby, job: @police, level: 3, url: "https://en.wikipedia.org/wiki/Chief_Wiggum", blurb: "Springfield Chief of Police.")
@lou=User.create(name: "Lou", public_id: 'lou', manager: @wiggum, job: @police, level: 2, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Eddie_and_Lou", blurb: "Springfield police officer.")
@eddie=User.create(name: "Eddie", public_id: 'eddie', manager: @lou, job: @police, level: 1, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Eddie_and_Lou", blurb: "Springfield police officer.")
@lovejoy=User.create(name: "Reverend Timothy Lovejoy", public_id: 'lovejoy', manager: @burns, job: @minister, url: "https://en.wikipedia.org/wiki/Reverend_Lovejoy", blurb: "Minister of the First Church of Springfield.")
@helen=User.create(name: "Helen Lovejoy", public_id: 'helen', manager: @lovejoy, job: @reverends_wife, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Helen_Lovejoy", blurb: "Reverend Lovejoy's wife.")
@carl=User.create(name: "Carl Carlson", public_id: 'carl', manager: @burns, job: @snpp_worker, url: "https://en.wikipedia.org/wiki/Carl_Carlson", blurb: "Springfield Nuclear Power Plant employee.")
@lenny=User.create(name: "Lenny Leonard", public_id: 'lenny', manager: @burns, job: @snpp_worker, url: "https://en.wikipedia.org/wiki/Lenny_Leonard", blurb: "Springfield Nuclear Power Plant employee; one of Homer Simpson's friends.")
@marge=User.create(name: "Marge Simpson", public_id: 'marge', manager: @lovejoy, job: @homemaker, url: "https://en.wikipedia.org/wiki/Marge_Simpson", blurb: "Wife of Homer; mother of Bart, Lisa, and Maggie.")
@homer=User.create(name: "Homer Simpson", public_id: 'homer', manager: @burns, job: @snpp_worker, url: "https://en.wikipedia.org/wiki/Homer_Simpson", blurb: "Husband of Marge; father of Bart, Lisa, and Maggie.")
@bart=User.create(name: "Bart Simpson", public_id: 'bart', manager: @marge, job: @hyperactive_child, url: "https://en.wikipedia.org/wiki/Bart_Simpson", blurb: "Eldest child of Homer and Marge; brother of Lisa and Maggie.")
@lisa=User.create(name: "Lisa Simpson", public_id: 'lisa', manager: @marge, job: @critical_thinker, url: "https://en.wikipedia.org/wiki/Lisa_Simpson", blurb: "Middle child and oldest daughter of Homer and Marge; sister of Bart and Maggie.")
@ralph=User.create(name: "Ralph Wiggum", public_id: 'ralph', manager: @lisa, job: @student, url: "https://en.wikipedia.org/wiki/Ralph_Wiggum", blurb: "Student at Springfield Elementary School.")
@atkins=User.create(name: "State Comptroller Atkins", public_id: 'atkins', manager: @bailey, job: @comptroller, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#State_Comptroller_Atkins", blurb: "State comptroller.")
@chalmers=User.create(name: "Gary Chalmers", public_id: 'chalmers', manager: @atkins, job: @educator, level: 3, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Superintendent_Chalmers", blurb: "Public schools superintendent.")
@skinner=User.create(name: "Principal Seymour Skinner", public_id: 'skinner', manager: @chalmers, job: @educator, level: 2, url: "https://en.wikipedia.org/wiki/Principal_Skinner", blurb: "Principal of Springfield Elementary School.")
@doris=User.create(name: "Lunchlady Doris", public_id: 'doris', manager: @skinner, job: @cafeteria_worker, url: "https://en.wikipedia.org/wiki/List_of_recurring_characters_in_The_Simpsons#Lunchlady_Doris", blurb: "Springfield Elementary School lunch lady.")

@brockman=User.create(name: "Kent Brockman", public_id: 'brockman', manager: @roger_meyers, job: @tv_personality, url: "https://en.wikipedia.org/wiki/Kent_Brockman", blurb: "Channel 6 News anchor.")
@comic_book_guy=User.create(name: "Comic Book Guy", public_id: 'comic_book_guy', manager: @radioactive_man, job: @shop_keep, url: "https://en.wikipedia.org/wiki/Comic_Book_Guy", blurb: "Proprietor of The Android's Dungeon comic book store. Name revealed to be Jeff Albertson in \"Homer and Ned's Hail Mary Pass\".")
@ned=User.create(name: "Ned Flanders", public_id: 'ned', manager: @lovejoy, job: @shop_keep, url: "https://en.wikipedia.org/wiki/Ned_Flanders", blurb: "The Simpson family's next door neighbor; owner of The Leftorium.")
@maude_flanders=User.create(name: "Maude Flanders", public_id: 'maude_flanders', manager: @ned, job: @homemaker, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Maude_Flanders", blurb: "Ned Flanders's deceased wife.")
@rod_flanders=User.create(name: "Rod Flanders", public_id: 'rod_flanders', manager: @ned, job: @oppressed_youth, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Rod_Flanders", blurb: "Ned and Maude Flanders's elder son.")
@todd_flanders=User.create(name: "Todd Flanders", public_id: 'todd_flanders', manager: @ned, job: @oppressed_youth, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Todd_Flanders", blurb: "Ned and Maude Flanders's younger son.")
@professor_john_frink=User.create(name: "Professor John Frink", public_id: 'professor_john_frink', manager: @bailey, job: @scientist, url: "https://en.wikipedia.org/wiki/Professor_Frink", blurb: "Scientist, inventor.")
@moe=User.create(name: "Moe Szyslak", public_id: 'moe', manager: @fat_tony, job: @tavern_keep, url: "https://en.wikipedia.org/wiki/Moe_Szyslak", blurb: "Owner of Moe's Tavern.")
@barney_gumble=User.create(name: "Barney Gumble", public_id: 'barney_gumble', manager: @moe, job: @drunkard, url: "https://en.wikipedia.org/wiki/Barney_Gumble", blurb: "Homer's drunken old pal.")
@hibbert=User.create(name: "Dr. Julius Hibbert", public_id: 'hibbert', manager: @bailey, job: @doctor, url: "https://en.wikipedia.org/wiki/Julius_Hibbert", blurb: "Medical doctor.")

@snyder=User.create(name: "Roy Snyder", public_id: 'snyder', manager: @bailey, job: @judge, url: "", blurb: "Old softie known for lenient punishments and unorthodox rulings.")
@harm=User.create(name: "Constance Harm", public_id: 'harm', manager: @bailey, job: @judge, url: "", blurb: "Harsh, unforgiving disciplinarian.")
@hutz=User.create(name: "Lionel Hutz", public_id: 'hutz', manager: @snyder, job: @attorney, url: "https://en.wikipedia.org/wiki/Lionel_Hutz", blurb: "Shyster of an attorney with an office in a strip mall.")
@gil=User.create(name: "Gil Gunderson", public_id: 'gil', manager: @hutz, job: @real_estate, url: "", blurb: "Crackpot real estate agent and paralegal.")

@hoover=User.create(name: "Elizabeth Hoover", public_id: 'hoover', manager: @skinner, job: @educator, level: 1, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Elizabeth_Hoover", blurb: "Lisa Simpson's teacher at Springfield Elementary School.")
@krabappel=User.create(name: "Edna Krabappel", public_id: 'krabappel', manager: @skinner, job: @educator, level: 1, url: "https://en.wikipedia.org/wiki/Edna_Krabappel", blurb: "Bart Simpson's teacher at Springfield Elementary School.")
@largo=User.create(name: "Dewey Largo", public_id: 'largo', manager: @skinner, job: @educator, level: 1, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Dewey_Largo", blurb: "Springfield Elementary School's music teacher.")
@willie=User.create(name: "Groundskeeper Willie", public_id: 'willie', manager: @skinner, job: @janitor, url: "https://en.wikipedia.org/wiki/Groundskeeper_Willie", blurb: "Janitor of Springfield Elementary School.")
@otto=User.create(name: "Otto Mann", public_id: 'otto', manager: @willie, job: @bus_driver, url: "https://en.wikipedia.org/wiki/Otto_Mann", blurb: "Springfield Elementary School bus driver.")

@johnny_tightlips=Athlete.create(name: "Johnny Tightlips", public_id: 'johnny_tightlips', manager: @fat_tony, job: @mob, level: 2, url: "https://en.wikipedia.org/wiki/Springfield_Mafia#Johnny_Tightlips", blurb: "One of Fat Tony's henchmen.")
@legs=Athlete.create(name: "Legs", public_id: 'legs', manager: @fat_tony, job: @mob, level: 1, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Legs_and_Louie", blurb: "Fat Tony's henchmen.")
@louie=Athlete.create(name: "Louie", public_id: 'louie', manager: @fat_tony, job: @mob, level: 1, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Legs_and_Louie", blurb: "Fat Tony's henchmen.")
@frankie_the_squealer=Athlete.create(name: "Frankie the Squealer", public_id: 'frankie_the_squealer', manager: @fat_tony, job: @mob, level: 2, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Frankie_the_Squealer", blurb: "Informant for Fat Tony.")

@leopold=User.create(name: "Leopold", public_id: 'leopold', manager: @chalmers, job: @secretary, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Leopold", blurb: "Superintendent Chalmers' assistant.")
@troy_mcclure=User.create(name: "Troy McClure", public_id: 'troy_mcclure', manager: @roger_meyers, job: @actor, url: "https://en.wikipedia.org/wiki/Troy_McClure", blurb: "Actor.")
@apu=User.create(name: "Apu Nahasapeemapetilon", public_id: 'apu', manager: @wiggum, job: @shop_keep, url: "https://en.wikipedia.org/wiki/Apu_Nahasapeemapetilon", blurb: "Operator of the Kwik-E-Mart.")
@arnie_pye=User.create(name: "Arnie Pye", public_id: 'arnie_pye', manager: @brockman, job: @helicopter_pilot, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Arnie_Pye", blurb: "Channel 6 helicopter reporter.")

@nelson=User.create(name: "Nelson Muntz", public_id: 'nelson', manager: @fat_tony, job: @school_bully, url: "https://en.wikipedia.org/wiki/Nelson_Muntz", blurb: "Springfield Elementary School bully.")
@jimbo=User.create(name: "Jimbo Jones", public_id: 'jimbo', manager: @nelson, job: @school_bully, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Jimbo_Jones", blurb: "Springfield Elementary School bully.")
@kearney=User.create(name: "Kearney Zzyzwicz", public_id: 'kearney', manager: @nelson, job: @school_bully, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Kearney_Zzyzwicz", blurb: "Springfield Elementary School bully.")

@milhouse=User.create(name: "Milhouse Van Houten", public_id: 'milhouse', manager: @bart, job: @student, url: "https://en.wikipedia.org/wiki/Milhouse_Van_Houten", blurb: "Bart Simpson's best friend; Student at Springfield Elementary School.")
@janey=User.create(name: "Janey Powell", public_id: 'janey', manager: @jimbo, job: @student, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Janey_Powell", blurb: "Student at Springfield Elementary School.")
@martin=User.create(name: "Martin Prince", public_id: 'martin', manager: @nelson, job: @student, url: "https://en.wikipedia.org/wiki/Martin_Prince", blurb: "Student at Springfield Elementary School.")
@wendell=User.create(name: "Wendell Borton", public_id: 'wendell', manager: @nelson, job: @student, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Wendell_Borton", blurb: "Student at Springfield Elementary School.")
@lewis=User.create(name: "Lewis Clark", public_id: 'lewis', manager: @jimbo, job: @student, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Lewis", blurb: "Student at Springfield Elementary School.")
@uter=User.create(name: "Üter", public_id: 'uter', manager: @kearney, job: @student, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#.C3.9Cter", blurb: "Student at Springfield Elementary School.")
@sherri=User.create(name: "Sherri", public_id: 'sherri', manager: @jimbo, job: @student, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Sherri_and_Terri", blurb: "Identical twin; Student at Springfield Elementary School.")
@terri=User.create(name: "Terri", public_id: 'terri', manager: @kearney, job: @student, url: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters#Sherri_and_Terri", blurb: "Identical twin; Student at Springfield Elementary School.")

# Exercise stuff
calves = IntervalSession.create(name: 'Calves', dt: '2023-05-23')
arms = IntervalSession.create(name: 'Arms', dt: '2023-05-27')
Attendance.create(athlete: @legs, interval_session: calves)
Attendance.create(athlete: @frankie_the_squealer, interval_session: arms)
